### ISSUE TITLE
Configure PostgreSQL Database Sync with Online Server

### ISSUE THREAD

**Issue by abhisanap19** [Dev-Connectivity/Node-Postgres-Learning-Platform#11]
- The current limitation of the local PostgreSQL database is impeding collaboration and hindering the efficient workflow of our development team. It cannot be accessed simultaneously by multiple developers, causing difficulties in working together effectively.
- To address this issue, we must establish a synchronization mechanism with an online server. Implementing database sync will provide all team members with access to an updated database, facilitating seamless collaboration and eliminating conflicts. 
- This improvement is essential for enhancing our development process and creating a more productive work environment.

### Expected Outcome:

Once the PostgreSQL database sync is configured with an online server, the development team will be able to work concurrently with an up-to-date database. This enhancement will facilitate collaboration, reduce conflicts, and improve the overall efficiency of our development workflow.

`I kindly request your attention to this issue as it would greatly benefit others in utilizing the synchronized data. Your assistance in resolving this matter is highly appreciated`

**Comment by Bhupi2508** [comment]
@abhisanap19, @PawarAditi The issue/enhancement has been updated. We have created a free PostgreSQL instance on ElephantSQL server where we can use up to 20MB for free. This allows us to keep all our data in sync. To obtain the database details, please contact us via email or provide your requirements, and we will provide the necessary information 🙂.

Feel free to raise any additional concerns or contribute further😇😇.
