### ISSUE TITLE
Inconsistent Table Creation Issue during "npm run setup" Command

### ISSUE THREAD

**Issue by gauravkotwal** [Dev-Connectivity/Node-Postgres-Learning-Platform#5]
### This inconsistency leads to an incomplete database schema, causing functionality issues within the application. We need to investigate and resolve this issue to ensure consistent creation of all required tables during the setup process.

 

- Steps to Reproduce:

 

    - Clone the repository.
    - Navigate to the project directory.
    - Run "npm run setup" to create the tables.
    - Check the console output and database to verify the number of tables created.

 

**Expected Behavior:**
The "npm run setup" command should consistently create all required tables, resulting in a complete and synchronized database schema.

 

**Current Behavior:**
Table creation during "npm run setup" is inconsistent, with varying numbers of tables created each time.

**Comment by Bhupi2508** [comment]
Issue has been fixed
